CREATE TABLE AKTIVITETER
(
    AKTIVITETID   VARCHAR(20) NOT NULL,
    AKTOERID      VARCHAR(20) NOT NULL,
    AKTIVITETTYPE VARCHAR(255),
    AVTALT        boolean DEFAULT true,
    FRADATO       TIMESTAMP,
    TILDATO       TIMESTAMP,
    OPPDATERTDATO TIMESTAMP,
    STATUS        VARCHAR(255),
    VERSION       NUMERIC(19),
    PRIMARY KEY (AKTIVITETID)
);
